### ISSUE TITLE
v2.0 Roadmap

### ISSUE THREAD

**Issue by lavrton** [SublimeText/CoffeeScript#90]
- [x] Lint support: https://github.com/aponxi/sublime-better-coffeescript/issues/58
- [x] Line number tracking: https://github.com/aponxi/sublime-better-coffeescript/issues/2
- [ ] Create Readme via https://github.com/aponxi/grunt-readme-generator #91 
- [x] Fix the else syntax thing #24
- [x] Auto create new column when spawning watchmode #88 
- [x] ~~Remove ST2 branch (ST3 is now public beta.)~~
